---
- name: Restore or Ensure RDS Instance from Snapshot
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    db_instance_identifier: wordpressdbclixxjenkins
    db_snapshot_identifier: wordpressdbclixxjenkins-1
    db_instance_class: db.t2.small
    security_group_id: sg-0dc66b0a42e0697da
    region: us-east-1

  tasks:
    - name: Ensure RDS instance is present and restored from snapshot
      community.aws.rds_instance:
        db_instance_identifier: "{{ db_instance_identifier }}"
        state: present
        db_snapshot_identifier: "{{ db_snapshot_identifier }}"
        db_instance_class: "{{ db_instance_class }}"
        engine: mysql
        region: "{{ region }}"
        vpc_security_group_ids:
          - "{{ security_group_id }}"
        publicly_accessible: yes
        skip_final_snapshot: yes
        wait: yes
      register: rds_result

    - name: Display RDS instance information
      debug:
        var: rds_result