---
- name: Restore or Ensure RDS Instance from Snapshot
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    db_instance_id: wordpressdbclixxjenkins
    db_snapshot_id: wordpressdbclixxjenkins-1
    security_group_id: sg-0dc66b0a42e0697da
    db_instance_type: db.t2.small
    subnet_group: default
    region: us-east-1

  tasks:
    - name: Ensure RDS instance is present and restored from snapshot
      community.aws.rds_instance:
        id: "{{ db_instance_id }}"
        state: present
        snapshot_id: "{{ db_snapshot_id }}"
        instance_type: "{{ db_instance_type }}"
        region: "{{ region }}"
        vpc_security_group_ids:
          - "{{ security_group_id }}"
        db_subnet_group_name: "{{ subnet_group }}"
        publicly_accessible: yes
        wait: yes
        skip_final_snapshot: yes
      register: rds_result

    - name: Display RDS instance information
      debug:
        var: rds_result